### ISSUE TITLE
Segmentation Fault when running

### ISSUE THREAD

**Issue by fala** [rlane/Oort-legacy#39]
Hey,

I'd like to try out your game, cause it sounds quite interesting for me. I'm trying to run in under Linux (Gentoo), and the installation process ran without any problem. But when I call "oort" under the shell I get:

> $ oort
> using data from /usr/local/share/oort
> Segmentation fault

Here's what GDB sais:

> Program received signal SIGSEGV, Segmentation fault.
> 0x0000000000416fd3 in oort_game_finalize (obj=<value optimized out>)
>     at game.c:1243
> 1243            g_assert (self->tasks->in_flight == 0);
> (...)
> (gdb) print self
> $1 = (OortGame *) 0x976120
> (gdb) print self->tasks
> $2 = (OortTaskPool *) 0x0
> (gdb) print self->tasks->in_flight
> Cannot access memory at address 0x18

Hope that it's helpful.

**Comment by rlane** [comment]
How did you get the source code? This bug has been fixed for a while. I've uploaded a new source tarball to the downloads page.
