### ISSUE TITLE
add refueling to carrier

### ISSUE THREAD

**Issue by rlane** [rlane/Oort-legacy#4]

**Comment by austinjames314** [comment]
Would this involve docking? If ships can dock with the carrier, then can they stay docked? If so, how many can be held? Or would this be something more like getting within a certain distance of the carrier and staying there for a period of time?

**Comment by rlane** [comment]
I'm not sure, I've thought about the alternatives a little. Docking could make things more complicated by making us keep track of the ships that are docked and handling edge cases like the carrier exploding. I think either automatic refueling within a small range or a special refuel (repair?) beam.

**Comment by austinjames314** [comment]
On one hand, docking lots of fighters and being able to launch them all at once has awesome on its side. But then there is also mass tracking to take care of, as well as the points you mentioned.  
On the other hand a repair/refuel beam has functional simplicity on its side. 
 It comes down to a game design decision. I vote docking personally, as my preference is towards more awesome, complexity be damned.
