### ISSUE TITLE
add universe boundary

### ISSUE THREAD

**Issue by rlane** [rlane/Oort-legacy#8]
Without a boundary around the map it would be possible for a player to send a ship flying fast enough that the other team wouldn't be able to catch up to it, ensuring that the other team can't win. Maybe we could just change the victory condition to count only the ships within a certain distance of the origin.

**Comment by austinjames314** [comment]
Hmm, definitely an area where the effect on how things play out should be carefully considered. I don't like the idea of a hard boundary that you bounce off or crash into. 
 The more I think about it, I think I like the idea of only counting ships within a certain radius of the origin towards the victory conditions.
